### ISSUE TITLE
在 Surge 配置中 SMTP 分流策略可能出现的问题

### ISSUE THREAD

**Issue by QingRex** [bunizao/TutuBetterRules#10]
在大多数机场审计规则下，SMTP发件服务总是被丢弃，所以选择SMTP策略直连是明智的。
但是在您的配置规则中，对于 SMTP 的 匹配规则是 DOMAIN-SUFFIX 这对于 Apple 原生邮件应用使用的诸如：p57-smtp.mail.me.com:587  类型并不能很好的支持。
建议修改为 KEYWORD 匹配，但是可能会造成一些难以预估的问题。
如果单独使用 Apple 邮件，个人建议并行直连该规则： https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/AppleMail/AppleMail.list
并且提示按照需求添加。
避免了 mail.me.com 跟随 Apple 规则走苹果服务分流造成的问题。
 此外，在隐藏 IP 分流中，Pro 配置对应位置已经修改为微博IP归属地规则，可以在简介中更新。
感谢作者的优秀规则。

**Comment by bunizao** [comment]
@QingRex 感谢您的反馈。

感觉对于apple的SMTP可以使用逻辑规则：

`AND,((DEST-PORT,587), (DOMAIN-SUFFIX,mail.me.com)),DIRECT`

此规则匹配域名后缀为 `mail.me.com` 且端口为 `587` 的请求。

由于我不常用Apple Mail，请尝试下这个规则是否有问题。感谢

**Comment by QingRex** [comment]
在使用了您提供的规则测试了邮件以后，邮件是可以正常发送的，新修改的规则并没有存在有关问题。
只是我不能确保所有人的发信端口都被绑定为587，故我测试表明在我的环境中执行正常，但是可能对于不同的发信服务器可能存在不一致的情况。
此外我观察到在使用发信服务时，连接主要是不同前缀的 mail.me.com 的网站，我建议需要 Apple Mail 使用需求的用户可以单独分流该域名，该域名在大陆地区访问是可以正常进行的。
感谢您的回复支持。

**Comment by bunizao** [comment]
SMTP的标准端口有 `25, 465, 587, 2525`，对于如今广泛应用的邮箱服务，包括自建的邮局服务，均使用这些端口与 SMTP 绑定。
所以，理论上可以暴力使用 `OR,((DEST-PORT,25), (DEST-PORT,2525), (DEST-PORT,465), (DEST-PORT,587)),DIRECT` 来匹配所有 SMTP 服务，但是由于 gmail 的 SMTP 服务器：`smtp.gmail.com:587` 在一些地区总是被阻断，所以全都指定端口直连不是一个妥善的做法。
我编写了一个域名集，这里包含大部分常用的邮箱的域名：[**Mail.list**](https://raw.githubusercontent.com/bunizao/TutuBetterRules/tutu/RuleList/DOMAlN/Mail.list)
最推荐的方式是把这个域名交给 Cloudflare WARP 处理，可以参照 https://github.com/VirgilClyne/Cloudflare 以在 Surge 中使用 WARP。

对于规则匹配问题，如果把 Mail 相关规则放在 Apple 规则前，Surge 会优先匹配 Mail 规则。

**Comment by QingRex** [comment]
感谢您的帮助，我将关闭这个 issue 因为我认为他得到了妥善的解决。
