### ISSUE TITLE
sub surge相关的模块现在全都无法通过url连接下载了，小白恳求可否更新下教程

### ISSUE THREAD

**Issue by kieranay** [bunizao/TutuBetterRules#8]
<img width="785" alt="CleanShot 2023-04-28 at 04 16 33" src="https://user-images.githubusercontent.com/90558709/234980987-be71670a-e606-45f7-876c-aa45f0d7309c.png">

**Comment by bunizao** [comment]
你好。
- 请先确定你所在的网络下可以正常链接 https://sub-store.vercel.app
- 请按照教程排查:
  - 请确认您已经正确配置并信任了系统根证书，并且已开启`MitM`、`Rewrite`、`脚本`。
  - 在浏览器中打开 https://sub.store/ 后进入Sub-Store，先添加单条订阅输入你的节点信息，然后添加组合订阅；
  - 组合订阅的命名一定要为Surge
